pipeline:
  name: remote-run
  identifier: remoterun
  projectIdentifier: DoNotDelete_Vikrant
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cd
        identifier: cd
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: <+input>
            serviceInputs: <+input>
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
          environments:
            metadata:
              parallel: true
            values:
              - environmentRef: vivekremoteenv
                gitBranch: main-patch-2
                environmentInputs:
                  identifier: vivekremoteenv
                  type: Production
                  variables:
                    - name: A
                      type: String
                      value: <+input>
                deployToAll: true
                infrastructureDefinitions: <+input>
              - environmentRef: remote11101
                gitBranch: main11101
                environmentInputs:
                  identifier: remote11101
                  type: Production
                  variables:
                    - name: B
                      type: String
                      value: <+input>
                    - name: C
                      type: String
                      value: <+input>
                deployToAll: true
                infrastructureDefinitions: <+input>
              - environmentRef: remote111015
                gitBranch: main11101-5
                environmentInputs:
                  identifier: remote111015
                  type: Production
                  variables:
                    - name: D
                      type: String
                      value: <+input>
                deployToAll: true
                infrastructureDefinitions: <+input>
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
