pipeline:
  name: vikrant-remote-2
  identifier: vikrantremote2
  projectIdentifier: DoNotDelete_Vikrant
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 20000m
        tags: {}
