pipeline:
  name: wed
  identifier: wed
  template:
    templateRef: remoteabhinav
    versionLabel: v1
    gitBranch: main-abhinav
    templateInputs:
      stages:
        - stage:
            identifier: ed
            template:
              templateInputs:
                type: Deployment
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
                  service:
                    serviceRef: <+input>
                    serviceInputs: <+input>
  tags: {}
  projectIdentifier: DoNotDelete_Vikrant
  orgIdentifier: default
